/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JTextFieldDateEditor;
import controlador.DevolucionControlador;
import java.awt.Component;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableRowSorter;
import modelo.Devolucion;
import modelo.DevolucionModelo;
import modelo.Prestamo;
import modelo.PrestamoModelo;
import util.PrestamoTableModel;
import util.UsuarioActual;

/**
 *
 * @author PC
 */
public class vistaDevolucion extends javax.swing.JFrame {

    /**
     * Creates new form vistaDevolucion
     */
    private DevolucionControlador controlador;

    private vistaDevolucion() {
        initComponents();
//        jdtPrestamo.setDate(new Date());
//        ((JTextFieldDateEditor) jdtPrestamo.getDateEditor()).setEditable(false);

    }

    public vistaDevolucion(String userType, int idUser) {
        initComponents();
        validarUsuario(userType, idUser);
        btnPagar.setVisible(false);
        actualizarEstadoBoton(idUser);
    }

    public void setControlador(DevolucionControlador controlador) {
        this.controlador = controlador;
    }

    public void actualizarEstadoBoton(int idUser) {

        try {
            DevolucionModelo modelo = new DevolucionModelo();
            BigDecimal mora = modelo.obtenerMoraUsuario(idUser);
            boolean tieneMora = mora.compareTo(BigDecimal.ZERO) > 0;
            btnPagar.setVisible(tieneMora);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al procesar la devolución: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jblID = new javax.swing.JLabel();
        jdtPrestamo = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaComentarios = new javax.swing.JTextArea();
        txtUsuario = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReservados = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cmbIDPrestamo = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("DEVOLUCIONES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 21, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Comentarios:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jblID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jblID.setText("ID de usuario:");
        getContentPane().add(jblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 131, -1, -1));

        jdtPrestamo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdtPrestamoPropertyChange(evt);
            }
        });
        getContentPane().add(jdtPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 192, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID de prestamo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de devolución:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En tiempo", "Atrasado" }));
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 80, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Estado de devolución:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        txtaComentarios.setColumns(20);
        txtaComentarios.setRows(5);
        jScrollPane1.setViewportView(txtaComentarios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 330, -1));
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, -1));

        tblReservados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblReservados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 90, 40));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 90, 40));

        cmbIDPrestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbIDPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        btnSalir.setText("Salir");
        btnSalir.setActionCommand("");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 90, 40));

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 90, 40));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 530, 90, 40));

        btnPagar.setText("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTabla() {
        PrestamoTableModel modelo = (PrestamoTableModel) tblReservados.getModel();
        tblReservados.setModel(modelo);

        TableRowSorter<PrestamoTableModel> sorter = new TableRowSorter<>(modelo);
        tblReservados.setRowSorter(sorter);

    }

    public void ajustarAnchoColumnas() {
        tblReservados.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        int minWidth = 100; // Establece un ancho mínimo para las columnas

        for (int column = 0; column < tblReservados.getColumnCount(); column++) {
            TableColumn tableColumn = tblReservados.getColumnModel().getColumn(column);
            int preferredWidth = tableColumn.getMinWidth();
            int maxWidth = tableColumn.getMaxWidth();

            for (int row = 0; row < tblReservados.getRowCount(); row++) {
                TableCellRenderer cellRenderer = tblReservados.getCellRenderer(row, column);
                Component c = tblReservados.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + tblReservados.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);

                if (preferredWidth >= maxWidth) {
                    preferredWidth = maxWidth;
                    break;
                }
            }

            preferredWidth = Math.max(preferredWidth, minWidth);
            tableColumn.setPreferredWidth(preferredWidth);
        }
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int idUsuario = Integer.parseInt(txtUsuario.getText());
        List<Prestamo> prestamos = DevolucionControlador.obtenerPrestamosPendientes(idUsuario);
        PrestamoTableModel model = new PrestamoTableModel(prestamos);

        cmbIDPrestamo.removeAllItems();

        for (Prestamo prestamo : prestamos) {
            cmbIDPrestamo.addItem(String.valueOf(prestamo.getId()));
            System.out.println(prestamo.getIdEjemplar());
        }

        tblReservados.setModel(model);
        ajustarAnchoColumnas();
        configurarTabla();

        DevolucionModelo modelo = new DevolucionModelo();

        try {
            BigDecimal morosidad = modelo.obtenerMoraUsuario(idUsuario);
            if (morosidad.compareTo(BigDecimal.ZERO) > 0) {
                btnPagar.setEnabled(true);
            } else {
                btnPagar.setEnabled(false);
            }
        } catch (SQLException e) {
            System.out.println("Ocurrio un error" + e);
        };


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:

        try {
            Devolucion devolucion = new Devolucion();
            Object selectedItem = cmbIDPrestamo.getSelectedItem();
            String selectedText = selectedItem.toString();
            int idPrestamo = Integer.parseInt(selectedText);
            devolucion.setIdPrestamo(idPrestamo);
            devolucion.setFechaDevolucion(jdtPrestamo.getDate());
            devolucion.setEstadoDevolucion(cmbEstado.getSelectedItem().toString());
            devolucion.setComentarios(txtaComentarios.getText());
            
            PrestamoModelo prestamo = new PrestamoModelo();
            Prestamo prestamoFecha = prestamo.obtenerPrestamoPorId(idPrestamo);
            Date fechaPrestamo = prestamoFecha.getFechaPrestamo();

            DevolucionControlador.procesarDevolucion(devolucion, fechaPrestamo, Integer.parseInt(txtUsuario.getText()), idPrestamo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al procesar la devolución: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        PrestamoTableModel modelo = (PrestamoTableModel) tblReservados.getModel();
        modelo.limpiarDatos();
        modelo.fireTableDataChanged();
        cmbIDPrestamo.removeAllItems();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        vistaMenu vista = new vistaMenu();
        vista.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        PrestamoTableModel modelo = (PrestamoTableModel) tblReservados.getModel();
        modelo.limpiarDatos();
        modelo.fireTableDataChanged();
        cmbIDPrestamo.removeAllItems();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jdtPrestamoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdtPrestamoPropertyChange
        // TODO add your handling code here:
//        if ("date".equals(evt.getPropertyName())) {
//            Date selectedDate = (Date) evt.getNewValue();
//            if (selectedDate != null) {
//                Date today = new Date();
//                // Comprueba si la fecha seleccionada es hoy, si no, vuelve a establecer la fecha de hoy.
//                if (selectedDate.compareTo(today) != 0) {
//                    jdtPrestamo.setDate(today);
//
//                }
//            }
//        }
    }//GEN-LAST:event_jdtPrestamoPropertyChange

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        try {
            int idUsuario = Integer.parseInt(txtUsuario.getText());
            Object selectedItem = cmbIDPrestamo.getSelectedItem();
            String selectedText = selectedItem.toString();
            int idPrestamo = Integer.parseInt(selectedText);
            DevolucionModelo modelo = new DevolucionModelo();

            BigDecimal mora = modelo.obtenerMoraUsuario(idUsuario);
            if (mora.compareTo(BigDecimal.ZERO) > 0) {
                modelo.registrarPago(idUsuario, mora, idPrestamo);
                JOptionPane.showMessageDialog(null, "Pago realizado con éxito. Deuda actualizada a cero.");
                actualizarEstadoBoton(idUsuario); // Actualiza el estado del botón después del pago
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error al realizar el pago: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void validarUsuario(String tipoUsuario, int idUsuario) {
        System.out.println(tipoUsuario);
        if (!"Administrador".equals(tipoUsuario)) {
            txtUsuario.setText(String.valueOf(idUsuario));
            txtUsuario.setEditable(false);

        }

        txtUsuario.setText(String.valueOf(idUsuario));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnPagar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbIDPrestamo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblID;
    private com.toedter.calendar.JDateChooser jdtPrestamo;
    private javax.swing.JTable tblReservados;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextArea txtaComentarios;
    // End of variables declaration//GEN-END:variables
}
